config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'music_folders#index'

  resources :music_folders, only: [:index, :show]

  resources :audio_files, only: [:show]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '*unmatched_route', :to => 'errors#raise_not_found!'

end

app/models/audio_file.rb
class AudioFile < ActiveRecord::Base
  belongs_to :music_folder

  dragonfly_accessor :file do
    storage_options {|a| { path: "audio_files/%s" % [ UUID.new.generate ] } }
  end
  
  searchable :artist, :album, :title, :genre, :year

  extend FriendlyId
  friendly_id :data_url

end

app/models/image.rb
class Image < ImageBase
  belongs_to :music_folder

  dragonfly_accessor :file do
    storage_options {|a| { path: "images/%s" % [ UUID.new.generate ] } }
    copy_to(:thumb){|a| a.thumb("300x250>") }
    copy_to(:thumb_high){|a| a.thumb("600x500>") }
  end

  dragonfly_accessor :thumb do
    storage_options {|a| { path: "thumbs/%s" % [ UUID.new.generate ] } }
  end

  dragonfly_accessor :thumb_high do
    storage_options {|a| { path: "thumbs/%s" % [ UUID.new.generate ] } }
  end
end

app/models/image_base.rb
class ImageBase < ActiveRecord::Base
  self.table_name = :images
end

app/models/music_folder.rb
class MusicFolder < ActiveRecord::Base
  has_many :audio_files, dependent: :destroy
  has_many :images, dependent: :destroy

  serialize :details, Hash

  searchable :formatted_name, :folder, :subfolder, :year

  extend FriendlyId
  friendly_id :data_url

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/audio_files_controller.rb
class AudioFilesController < ApplicationController
  before_action :set_audio_file
  before_action :create_file
  before_action :create_m3u8

  def show
    respond_to do |format|
      format.json do
        render json: @audio_file.to_json,
          layout: false
      end
    end
  end

    private

  def set_audio_file
    @audio_file = AudioFile.find_by(data_url: params[:id]).decorate
  end

  def create_file
    if !@audio_file.file && !RedisDb.client.get("encode:#{@audio_file.id}")
      RedisDb.client.setex "encode:#{@audio_file.id}", 120, 1
      EncodeWorker.perform_async @audio_file.id
    end
  end

  def create_m3u8
    if @audio_file.file && !@audio_file.m3u8_exists? && !RedisDb.client.get("stream:#{@audio_file.id}")
      RedisDb.client.setex "stream:#{@audio_file.id}", 120, 1
      StreamWorker.perform_async @audio_file.id, @audio_file.file.path
    end
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def raise_not_found!
    render file: "#{Rails.root}/public/404.html", status: 400, layout: false
  end
end

app/controllers/music_folders_controller.rb
class MusicFoldersController < ApplicationController
  require Rails.root.join "lib/helpers/search_helpers"
  include SearchHelpers

  before_action :session_store
  before_action :session_load

  attr_accessor :search_params
  helper_method :search_params

  before_action :set_time, only: [:index]
  before_action :search_music_folders, only: [:index]

  before_action :set_music_folder, only: [:show]
  before_action :set_audio_files, only: [:show]

  def index
    respond_to do |format|
      format.html
      format.json do
        render json: @music_folders.to_json,
          layout: false
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json do
        render json: @audio_files.to_json,
          layout: false
      end
    end
  end

  private

  def set_music_folder
    @music_folder = MusicFolder.find_by(data_url: params[:id]).decorate
  end

  def set_audio_files
    @audio_files = @music_folder.audio_files.decorate.sort { |a, b| a.number <=> b.number }.map &:attributes
  end

  def set_time
    @t1 = Time.now
  end

  def permitted_params
    params.permit :format, :q, :folder, :subfolder, :utf8
  end

  def session_store
    session[:search_params] = permitted_params.to_hash.compact.to_json if permitted_params.to_hash.compact.any?
  end

  def session_load
    @search_params = session[:search_params] ? JSON.parse(session[:search_params], symbolize_names: true) : {}
  end

  def search_music_folders
    @music_folders = search_params.values.all?(&:blank?) ? [] : search_db(parse_search_params(search_params))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_transition
    { "data-transition" => "none" }
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :name => 'viewport', :content => 'width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0' }
    = stylesheet_link_tag :application, media: :all
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head) if defined?(:head)
  %body
    = yield

app/views/music/_images.css.erb
@mixin image-set($url_lowres, $url_highres) {
  background-image: url($url_lowres);
  background-image: -webkit-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  background-image:    -moz-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  background-image:     -ms-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  background-image:      -o-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  @content;
}

<% @release.images.each do |image| %>
  #<%= "img-" + image.id.to_s %> {
    @include image-set('<%= image.thumb.url %>', '<%= image.thumb_high.url %>') {
      width: <%= image.thumb.width %>px;
      height: <%= image.thumb.height %>px;
    }
  }
<% end %>

app/views/music/search.html.haml
- content_for :head do
  = javascript_include_tag :music
  = stylesheet_link_tag :music

%div{ 'data-role': 'page', 'id': 'search' }
  .container
    = form_tag music_index_path, default_transition.merge(method: :get, 'data-method': :get) do
      .form-group
        .col-md-5
          = text_field_tag :q, params[:q], class: 'form-control', type: 'search'
        .col-md-5
          %button.btn.btn-default{ type: 'submit' } Search
    .clear

    %ol.search
      - @releases.each do |item|
        %li
          %h5
            .label.label-primary= link_to item.year, item.year_url, default_transition
            %span.label.label-info
              = link_to item.folder_name, item.folder_url, default_transition
              - if item.subfolder_url
                |
                = link_to item.subfolder_name, item.subfolder_url, default_transition
            %span.link
              = link_to highlight(item.formatted_name, search_terms_array), item.url

    %small.margin-20
      = 'Page rendered in %s seconds - %s' % [ Time.now - @t1, Time.now ]

app/views/music/stats.html.haml
- content_for :head do
  = javascript_include_tag "//google.com/jsapi"

.container

  .row
    = form_tag stats_music_index_path, method: :get do
      .form-group
        .col-md-2.col-xs-2
          %p
            = select_tag :m2, options_for_select(ALLOWED_METRICS.map{|name| [name.titleize, name] }, selected: @metric2)
          %p
            = select_tag :m1, options_for_select(ALLOWED_METRICS.map{|name| [name.titleize, name] }, selected: @metric1)
        .col-md-2.col-xs-2
          %button.btn.btn-default{ type: "submit" } Update

  .row
    .col-md-8.col-xs-8
      #chart_div

:javascript

  google.load('visualization', '1', {packages: ['corechart', 'bar']});
  google.setOnLoadCallback(drawStacked);

  function drawStacked() {

    var data = google.visualization.arrayToDataTable(
      #{([["Metric"] + @metrics1] + @data).to_json}
    );

    var options = {
      width: 1000,
      height: 700,
      legend: { position: 'top', maxLines: 3 },
      bar: { groupWidth: '75%' },
      isStacked: true,
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
    chart.draw(data, options);

  }

app/views/music_folders/_audio_files.html.haml
.audio_files
  - @audio_files.each do |audio_file|
    .row{ class: cycle('odd', 'even') }
      %ul
        %li
          .col-md-2
            = link_to audio_file.artist, audio_file.artist_url, default_transition
          .col-md-2
            = audio_file.title
          .col-md-2
            = audio_file.album
          .col-md-1
            = audio_file.genre
          .col-md-1
            .badge
              = link_to audio_file.year, audio_file.year_url, default_transition
          .col-md-1
            .badge
              = audio_file.duration
          .col-md-1
            %i{ class: "fas fa-3 fa-spin %s hidden" % FA_CSS[:processing] }
            %i{ class: "fab fa-3 %s" % FA_CSS[:play], data: { id: audio_file.id } }

:javascript
  new App.AudioFiles(#{@audio_files.map(&:marshal_dump).to_json.html_safe})
  new App.AudioFilesRows('.audio_files > .row')

app/views/music_folders/_images.html.haml
:scss
  #{render partial: "music_folders/images.scss"}

.images
  - if @music_folder.images.any?
    .row
      .polaroid-images
        - @music_folder.images.each do |image|
          = link_to image.file.url, class: :swipebox do
            %div{ id: "img-#{image.id}" }

:javascript
  $(document).ready(function(e) {
    observe_polaroids();
  });

app/views/music_folders/_images.scss.erb
@mixin image-set($url_lowres, $url_highres) {
  background-image: url($url_lowres);
  background-image: -webkit-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  background-image:    -moz-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  background-image:     -ms-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  background-image:      -o-image-set(url($url_lowres) 1x, url($url_highres) 2x);
  @content;
}

<% @music_folder.images.each do |image| %>
  #<%= "img-" + image.id.to_s %> {
    @include image-set('<%= image.thumb.url %>', '<%= image.thumb_high.url %>') {
      width: <%= image.thumb.width %>px;
      height: <%= image.thumb.height %>px;
    }
  }
<% end %>

app/views/music_folders/index.html.haml
- content_for :head do
  = javascript_include_tag :layout
  = stylesheet_link_tag :layout

%div{ 'data-role': 'page' }
  .container
    = form_tag music_folders_path, default_transition.merge(method: :get) do
      .form-group
        .col-md-5
          = text_field_tag :q, search_params[:q], class: 'form-control', type: 'search'
        .col-md-5
          %button.btn.btn-default{ type: 'submit' } Search
    .clear

    - cache search_params do
      %ol.search
        - @music_folders.each do |item|
          %li
            %h5
              .label.label-primary= link_to item.year, item.year_url, default_transition
              %span.label.label-info
                = link_to item.folder_name, item.folder_url, default_transition
                - if item.subfolder
                  |
                  = link_to item.subfolder_name, item.subfolder_url, default_transition
              %span.link
                = link_to item.name, item.url

    .footer
      %small
        = 'Page rendered in %s seconds - %s' % [ Time.now - @t1, Time.now ]

app/views/music_folders/show.html.haml
- content_for :head do
  = javascript_include_tag :layout
  = stylesheet_link_tag :layout

%div{ 'data-role': 'page' }
  .back
    .row
      %ul
        %li
          = link_to music_folders_path(search_params), default_transition do
            %i.fas.fa-4.fa-list

  - cache @music_folder do
    = render partial: 'music_folders/images'
    = render partial: 'music_folders/audio_files'